### ISSUE TITLE
Trying to replace DWA with teb_local_planner for Clearpath Husky

### ISSUE THREAD

**Issue by aarontan-git** [rst-tu-dortmund/teb_local_planner#76] opened 2018-06-12 15:30 UTC
Hello,

I am following this [tutorial ](http://wiki.ros.org/teb_local_planner/Tutorials/Configure%20and%20run%20Robot%20Navigation) for a clearpath husky a200 mobile robot.

I have edited the move_base.launch file by adding below line as described by the tutorial:

`<arg name="base_local_planner" default="teb_local_planner/TebLocalPlannerROS" />`

And I have also updated the planner.yaml file by adding the following to the end of the file: (as described by the tutorial)

----------------------------------------------------------------------------------------------------------------------------------
TebLocalPlannerROS:

 odom_topic: odom
 map_frame: /odom
    
 //Trajectory
  
 teb_autosize: True
 dt_ref: 0.3
 dt_hysteresis: 0.1
 global_plan_overwrite_orientation: True
 max_global_plan_lookahead_dist: 3.0
 feasibility_check_no_poses: 5
    
 //Robot
         
 max_vel_x: 0.4
 max_vel_x_backwards: 0.2
 max_vel_theta: 0.3
 acc_lim_x: 0.5
 acc_lim_theta: 0.5
 min_turning_radius: 0.0
 footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
   type: "point"
   radius: 0.2 # for type "circular"
   line_start: [-0.3, 0.0] # for type "line"
   line_end: [0.3, 0.0] # for type "line"
   front_offset: 0.2 # for type "two_circles"
   front_radius: 0.2 # for type "two_circles"
   rear_offset: 0.2 # for type "two_circles"
   rear_radius: 0.2 # for type "two_circles"
   vertices: [ [0.25, -0.05], [0.18, -0.05], [0.18, -0.18], [-0.19, -0.18], [-0.25, 0], [-0.19, 0.18], [0.18, 0.18], [0.18, 0.05], [0.25, 0.05] ] # for type "polygon"

 //GoalTolerance
    
 xy_goal_tolerance: 0.2
 yaw_goal_tolerance: 0.1
 free_goal_vel: False
    
 //Obstacles
    
 min_obstacle_dist: 0.4
 include_costmap_obstacles: True
 costmap_obstacles_behind_robot_dist: 1.0
 obstacle_poses_affected: 30
 costmap_converter_plugin: ""
 costmap_converter_spin_thread: True
 costmap_converter_rate: 5

 //Optimization
    
 no_inner_iterations: 5
 no_outer_iterations: 4
 optimization_activate: True
 optimization_verbose: False
 penalty_epsilon: 0.1
 weight_max_vel_x: 2
 weight_max_vel_theta: 1
 weight_acc_lim_x: 1
 weight_acc_lim_theta: 1
 weight_kinematics_nh: 1000
 weight_kinematics_forward_drive: 1
 weight_kinematics_turning_radius: 1
 weight_optimaltime: 1
 weight_obstacle: 50
 weight_dynamic_obstacle: 10 # not in use yet
 alternative_time_cost: False # not in use yet

 //Homotopy Class Planner

 enable_homotopy_class_planning: True
 enable_multithreading: True
 simple_exploration: False
 max_number_classes: 4
 roadmap_graph_no_samples: 15
 roadmap_graph_area_width: 5
 h_signature_prescaler: 0.5
 h_signature_threshold: 0.1
 obstacle_keypoint_offset: 0.1
 obstacle_heading_threshold: 0.45
 visualize_hc_graph: False

------------------------------------------------------------------------------------------------------------------
When I launch the husky_empty_world, husky_viz for rviz, and the mentioned move base file, I am still unable to teb_local_planner as an option in local planner. The only one I see is still DWA. I am wondering, how do I replace the DWA planner with the teb_local_planner?

Thank you.
Aaron

**Comment by aarontan94** [comment] 2018-06-12 15:38
<launch>

  <arg name="no_static_map" default="false"/>

  <arg name="base_global_planner" default="navfn/NavfnROS"/>
  <arg name="base_local_planner" default="teb_local_planner/TebLocalPlannerROS" />
  
  

  <node pkg="move_base" type="move_base" respawn="false" name="move_base" output="screen">

    <param name="base_global_planner" value="$(arg base_global_planner)"/>
    <param name="base_local_planner" value="$(arg base_local_planner)"/>  
    <rosparam file="$(find husky_navigation)/config/planner.yaml" command="load"/>

    
    <rosparam file="$(find husky_navigation)/config/costmap_common.yaml" command="load" ns="global_costmap" />
    <rosparam file="$(find husky_navigation)/config/costmap_common.yaml" command="load" ns="local_costmap" />

    
    <rosparam file="$(find husky_navigation)/config/costmap_local.yaml" command="load" ns="local_costmap" />
    <param name="local_costmap/width" value="10.0"/>
    <param name="local_costmap/height" value="10.0"/>

    
    <rosparam file="$(find husky_navigation)/config/costmap_global_static.yaml" command="load" ns="global_costmap" unless="$(arg no_static_map)"/>
    
    
    <rosparam file="$(find husky_navigation)/config/costmap_global_laser.yaml" command="load" ns="global_costmap" if="$(arg no_static_map)"/>
    <param name="global_costmap/width" value="100.0" if="$(arg no_static_map)"/>
    <param name="global_costmap/height" value="100.0" if="$(arg no_static_map)"/>
  </node>

</launch>

**Comment by croesmann** [comment] 2018-06-12 16:26
I am not sure where you have set 
   `<arg name="base_local_planner" default="teb_local_planner/TebLocalPlannerROS" />`
 but this is just an option for a [command-line provided argument](http://wiki.ros.org/roslaunch/XML/arg) in a launch file. Are you loading the parameter correctly?

You should rather check that the parameter is loaded as follows:
```
<node type="move_base"...>
  <!-- All the other move base parameters -->
  <param name="base_local_planner" value="teb_local_planner/TebLocalPlannerROS" />
</node>
```

or in case of your command-line argument:
`<param name="base_local_planner" value="$(arg base_local_planner)" />`.

**Comment by aarontan-git** [comment] 2018-06-12 17:14
Hello @croesmann , 

This is how I added to my launch file; however, this didn't solve the issue

![launch file](https://user-images.githubusercontent.com/35575286/41305955-8bb004b6-6e42-11e8-9765-10013634188d.png)

Aaron

**Comment by croesmann** [comment] 2018-06-13 09:52
I am not familiar with the husky navigation package. Maybe check if they load everything properly in their husky package code.

And please also make sure that the teb_local_planner is installed:
Is the planner listed if you invoke the following command:
```
rospack plugins --attrib=plugin nav_core
```

Note, theTebLocalPlannerROS parameters in your planner.yaml have a wrong indentation. Is it just a copy and paste error? This should not affect the plugin loading, but your supplied parameter configuration could be ignored afterward.

I close this issue for now, since to my mind the issue is not related to the teb_local_planner itself. But to a correct move_base / husky configuration. Please feel free to add further comments.

edit: you can find working configurations in the [teb_local_planner_tutorials](https://github.com/rst-tu-dortmund/teb_local_planner_tutorials) package.

Another hint for later: I had a short look at the husky package. You likely need to reduce the local comstap resolution because otherwise the CPU time for the planner could be too long.

**Closed as completed by croesmann** 2018-06-13 09:52 UTC

**Comment by aarontan94** [comment] 2018-06-13 19:46
Hello @croesmann 

I believe the indentation has something to do with my previous error. I have fixed the indentation in the planner.yaml file and tried to launch the move_base again. This time I get an error that says

`load_parameters: unable to set parameters (last param was [/move_base/TebLocalPlannerROS/obstacle_keypoint_offset=0.1]): cannot marshal None unless allow_none is enabled
`
Do you know why this may be?

**Comment by aarontan94** [comment] 2018-06-13 19:52
Also, when I run `rospack plugins --attrib=plugin nav_core`

I get the following:
move_slow_and_clear /opt/ros/kinetic/share/move_slow_and_clear/recovery_plugin.xml
base_local_planner /opt/ros/kinetic/share/base_local_planner/blp_plugin.xml
navfn /opt/ros/kinetic/share/navfn/bgp_plugin.xml
rotate_recovery /opt/ros/kinetic/share/rotate_recovery/rotate_plugin.xml
dwa_local_planner /opt/ros/kinetic/share/dwa_local_planner/blp_plugin.xml
clear_costmap_recovery /opt/ros/kinetic/share/clear_costmap_recovery/ccr_plugin.xml
teb_local_planner /opt/ros/kinetic/share/teb_local_planner/teb_local_planner_plugin.xml
global_planner /opt/ros/kinetic/share/global_planner/bgp_plugin.xml
carrot_planner /opt/ros/kinetic/share/carrot_planner/bgp_plugin.xml
