### ISSUE TITLE
some issues occured accidental。

### ISSUE THREAD

**Issue by asimay** [rst-tu-dortmund/teb_local_planner#9] opened 2016-06-07 10:29 UTC
[ INFO] [1465295128.429697743, 456.200000000]: GOAL Reached!
[ WARN] [1465295133.355418858, 461.100000000]: TebLocalPlannerROS: trajectory is not feasible. Resetting planner...
[ WARN] [1465295134.000557437, 461.700000000]: TebLocalPlannerROS: trajectory is not feasible, but the planner suggests a shorter horizon temporary. Complying with its wish for at least 10s...
[ INFO] [1465295144.194776376, 471.900000000]: Switching back to full horizon length.
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
[ WARN] [1465295163.258694130, 491.000000000]: TebLocalPlannerROS: trajectory is not feasible, but the planner suggests a shorter horizon temporary. Complying with its wish for at least 10s...
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int_): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
int g2o::csparse_extension::cs_cholsolsymb(const cs_di_, double_, const cs_dis_, double_, int*): cholesky failed!
Cholesky failure, writing debug.txt (Hessian loadable by Octave)
[ INFO] [1465295173.290844396, 501.000000000]: Switching back to full horizon length.
[ INFO] [1465295176.760568540, 504.500000000]: GOAL Reached!

when I set aim is in the middle of two block obstacle. but finally goal reached at last line above.
![44](https://cloud.githubusercontent.com/assets/8703449/15854661/a5026b46-2cdd-11e6-8415-2d6a5fa4a45a.png)

Thanks!

**Comment by asimay** [comment] 2016-06-07 10:34
error snapshot: 
![55](https://cloud.githubusercontent.com/assets/8703449/15854807/6fde1dba-2cde-11e6-8dfd-8008c51d2b91.png)

**Comment by croesmann** [comment] 2016-06-15 14:24
In commit 069c230b11513cd3077 I fixed a crucial bug concerning the navigation behavior close to the goal. This could also resolve your issue mentioned here. I cherry-picked this fix to indigo and jade as well.

**Comment by asimay** [comment] 2016-06-17 09:16
hi, dear @croesmann, I download your new code and test. it works very good! and no "cholesky failed" info printed any more. please see below test snapshot.
![33](https://cloud.githubusercontent.com/assets/8703449/16146110/fb150bf0-34ae-11e6-8315-7d0f0c136f21.png)

sometimes the teb path still cross the wall when I set the goal very close to the inflation layer. but occured very rarely compared with last version.
please see below snapshot:
![22](https://cloud.githubusercontent.com/assets/8703449/16146145/3007abb0-34af-11e6-83ec-af271a3a80a9.png)

**Comment by croesmann** [comment] 2016-11-15 16:36
Since I pushed some significant changes to kinetic-devel since your last post, I close this issue know.
If the issue is still present, we can reopen this issue. Please let me know in that case by leaving a comment here ;-)

**Closed as completed by croesmann** 2016-11-15 16:36 UTC
